stages:
  - make_all
  - make_test
  - projet_test_sh

make_all:
  image: gcc:latest
  stage: make_all
  script:
    - make all

make_test:
  image: gcc:latest
  stage: make_test
  script:
    - make test

projet_test_sh:
  image: gcc:latest
  stage: projet_test_sh
  script:
    - apt-get update -qy
    - apt-get install -y valgrind
    - ./Projet_test.sh